Repository TeamObjects/Market-Bridge-FE, pull requests merged in 2024-03, with the labels that each got.

#22 Design : 장바구니 페이지
  next.config.js
  public/svgs/close.svg
  public/svgs/index.ts
  public/svgs/shoppingCart.svg
  src/api/cartApi.ts
  src/app/cart/page.tsx
  src/components/(cart)/CartItem.tsx
  src/components/(cart)/CartList.tsx
  src/components/shared/Header.tsx
Labels: 🎨 Style

#24 마이페이지 중 [배송지 관리, 개인정보 수정 페이지] 기능구현
  .yarn/cache/react-daum-postcode-npm-3.1.3-95dbfacabd-559c2463b3.zip
  .yarn/install-state.gz
  package.json
  src/api/mypageApi.ts
  src/app/(auth)/mypage/address/page.tsx
  src/components/(auth)/(mypage)/(address)/AddressList.tsx
  src/components/(auth)/(mypage)/(address)/AddressListHeader.tsx
  src/components/(auth)/(mypage)/(address)/AddressListItem.tsx
  src/components/(auth)/(mypage)/(address)/AddressListItems.tsx
  src/components/(auth)/(mypage)/(address)/AddressPopUp.tsx
  src/components/(auth)/(mypage)/MyPageNavButton.tsx
  src/components/shared/Alert.tsx
  src/components/shared/BackDrop.tsx
  src/contexts/AlertContext.tsx
  src/recoil/authAtom.ts
  yarn.lock
Labels: 🔧 Fix, ♻️ Refactor, ✨ Feature

#25 Setting : 이미지 도메인 설정
  next.config.js
Labels: ⚙️ Config

#32 Feat : 장바구니 기능 및 UI 구현
  src/components/(cart)/CartAddress.tsx
  src/components/(cart)/CartInformation.tsx
  src/components/(cart)/CartItem.tsx
  src/components/(cart)/CartList.tsx
  src/components/(cart)/CartPayInformation.tsx
  src/constants/constants.ts
  src/recoil/cartAtom.ts
  yarn.lock
Labels: ✨ Feature
